### ISSUE TITLE
Histogrammar pyROOT: AttributeError: 'StackedHistogramMethods' object has no attribute 'cuts'

### ISSUE THREAD

**Issue by vincecr0ft** [histogrammar/histogrammar-python#25]
Hi there, I've been trying to get started with using Histogrammar. It looks really pretty and very useful!

If people have a CERN account you should be able to see how far I got by clicking on this link.
[![here's a picture](https://cernbox.cern.ch/core/img/actions/badge_swan_white_150.svg)](https://cern.ch/swanserver/cgi-bin/go/?projurl=https://github.com/vincecr0ft/Histogrammar.git)  also visible [here](https://cernbox.cern.ch/index.php/s/ldHCUpOlO28sJuQ) but with that first link (you might have to log into SWAN first then) this will clone the repo and run within the service.

buuut. I only got as far as using the suite of stacked or overlaid histogram substructures including `histogrammar.Stack` and `histogrammar.partition`

The issue as stated in the title is:

> `AttributeError: 'StackedHistogramMethods' object has no attribute 'cuts'`

or in full:

> `AttributeErrorTraceback (most recent call last)
<ipython-input-24-bc2e1823d27d> in <module>()
      6     stack.fill(event)
      7
----> 8 roothist = stack.plot.root("name12", "name13", "name14", "name15", "name16")
      9 for i, h in enumerate(roothist.values()):
     10     h.SetFillColor(i + 2)
>
>/eos/user/v/vcroft/.local/lib/python2.7/site-packages/histogrammar/plot/root.pyc in plotroot(self, *names)
    190         import ROOT
    191         out = OrderedDict()
--> 192         for n, (c, v) in zip(names, self.cuts):
    193             if isinstance(n, (list, tuple)) and len(n) == 2:
    194                 name, title = n
>
>AttributeError: 'StackedHistogramMethods' object has no attribute 'cuts'`

It's my first day with Diana-hep so give me a couple of days and I can probably give you some more useful comments than 'I did the thing and it didn't work' but until then perhaps I'm doing something wrong that is simple to fix.

If there is any way I can contribute a little more other than beta testing please let me know. I was hoping to get through these tutorials then utilise the pySpark interface setup in SWAN for fast parallelised histogramming.

**Comment by vincecr0ft** [comment]
This is with the histogrammar install on pypy

**Comment by jpivarski** [comment]
Hi Vince! Welcome to the team! (Actually, if you'd like to talk about projects, I can give you an overview of what everyone's working on in a Skype or Vidyo call. Just email me at pivarski@fnal.gov. We can also talk about HistFitter.)

Anyway, you have likely found a real bug, though just a renaming one. Getting to version 1.0 of the Histogrammar spec, some attribute names changed. Probably an easy way to diagnose it is to compare the Python version with the Scala version— the Scala compiler wouldn't let a name change bug slip past compilation.

**Comment by vincecr0ft** [comment]
ok so everything in the specification is fine. It's particular to the root bindings. The property `cuts` has become `thresholds.`

https://github.com/histogrammar/histogrammar-python/blob/master/histogrammar/plot/root.py#L192

**Comment by jpivarski** [comment]
Thanks! I'll take care of it at some point, out you can submit a pull request against the 1.0.x branch of you want. It bottlenecks through me, anyway, since I have to do the release.

**Comment by vincecr0ft** [comment]
The pull request was labeled above as #26 it's passed all the compilation tests except python 2.6

**Comment by jpivarski** [comment]
Bokeh doesn't work in Python 2.6. The test is already deactivated in the testing suite, but apparently even installing Bokeh fails now (it didn't before). I modified the .travis.yaml; you can pull in this commit (PR #27).

**Comment by jpivarski** [comment]
Yes, that passed Travis. Go ahead and pull the one-line change into your .travis.yaml and resubmit. Thanks!
