### ISSUE TITLE
Undefined variable in Select

### ISSUE THREAD

**Issue by PerilousApricot** [histogrammar/histogrammar-python#31]
The following line of code

https://github.com/histogrammar/histogrammar-python/blob/master/histogrammar/primitives/select.py#L230

references `quantity`, though I believe it should be `self.quantity`

**Comment by PerilousApricot** [comment]
I verified I can monkeypatch the function to use self.quantity, which works.

**Comment by jpivarski** [comment]
Thanks for reporting this! I've pushed it to the 1.x branch.
