### ISSUE TITLE
Question: does this use numpy histograms?

### ISSUE THREAD

**Issue by dguest** [histogrammar/histogrammar-python#32]
I was looking to use this to get around a simple issue that I have with numpy histograms: specifically, numpy histograms work by calculating a cumulative sum across the bin ranges, which means that when weights vary by a factor of 10e6 or so from one end of the spectrum to the other (i.e. in simulated LHC dijet spectra) the low-weight end is lost to roundoff error.

I took a look and it wasn't clear if numpy histograms are being used behind the scenes. If not, great, this is probably exactly what I need. If so, also great, because as part of this project we should probably fix numpy histograms.

**Comment by jpivarski** [comment]
This does not use Numpy histograms.

However, I'm in the process of deprecating Histogrammar in favor of [histbook](https://github.com/scikit-hep/histbook), which also doesn't use Numpy histograms. histbook uses Numpy arrays to store and manipulate aggregated data, but the actual bin updates are performed with `numpy.add.at`, nothing cumulative.
