### ISSUE TITLE
python docs and examples

### ISSUE THREAD

**Issue by jpata** [histogrammar/histogrammar-python#6]
Looking at http://histogrammar.org/python/0.8.0/, the user is first greeted with the arcane

*All aggregation primitives descend from two classes, Container and Factory. Container defines all the methods for the primitive to aggregate and contain data, while Factory has methods for making containers. (In other languages, the two roles are distinct.)*

It would be great if there would be some concrete examples on how to do various kinds of histogramming tasks, with perhaps numpy or ROOT alternatives on the side as kind of a Rosetta stone.

**Comment by jpivarski** [comment]
I don't know how you ended up there first (Python reference docs, generated from docstrings) instead of http://histogrammar.org/docs/tutorials/ , but the Tutorials site addresses your question about examples and comparisons to ROOT.

**Comment by jpata** [comment]
OK, thanks, I hadn't seen these tutorials. I went histogrammar.org -> documentation -> python reference.

**Comment by jpivarski** [comment]
I see. I guess that does make sense. I've got Google Analytics running on this website, so we'll see if large volumes of people follow that path and get confused. Generally, I've taken the word "reference" to mean deep details that you look up when you have to and "tutorial" to mean first steps. If this is a problem, I could add a sentence at the top of the reference landing pages saying, "Go see the tutorials if you're confused."

**Comment by jpivarski** [comment]
(Thanks, though!)
