### ISSUE TITLE
No tests with Spark in build pipeline

### ISSUE THREAD

**Issue by mkopec87** [histogrammar/histogrammar-python#67]
Tests from 'test_spark_histogrammar.py' are not executed as part of build pipeline.

**Comment by mbaak** [comment]
Yes. I've learned by now that this is possible. (We turn the spark tests on for entitymatching as well.)
I'll fix this (= will ask Simon how to do this) when your PR is in.

**Comment by mbaak** [comment]
I will follow up with this.

**Comment by mbaak** [comment]
Resolved with: 
https://github.com/histogrammar/histogrammar-python/pull/68
